import { GoogleGenAI, Chat } from '@google/genai';
import { SYSTEM_INSTRUCTION } from '../constants';

// Initialize the SDK. Assumes process.env.API_KEY is available in the environment.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY, vertexai: true });

export const createEmbeddedChatSession = (): Chat => {
    return ai.chats.create({
        model: 'gemini-2.5-flash',
        config: {
            systemInstruction: SYSTEM_INSTRUCTION,
            temperature: 0.2, // Slightly increased to allow better flow for long reports while remaining factual
            tools: [{ googleSearch: {} }], // Enable Google Search grounding for real-time board pricing
        }
    });
};

export const generateCircuitImage = async (prompt: string): Promise<string> => {
    // Extract a shorter subject for the image prompt to avoid Imagen token/character limits
    let coreSubject = prompt;
    if (prompt.length > 100) {
        coreSubject = prompt.substring(0, 100) + "...";
    }

    let stylePrompt = coreSubject;
    const lowerPrompt = prompt.toLowerCase();
    
    // Inject specific style instructions based on the type of diagram requested
    if (lowerPrompt.includes('block diagram')) {
        stylePrompt = `A clean, flat 2D technical block diagram of: ${coreSubject}. Style: Professional engineering diagram, use simple colored rectangular boxes for subsystems, connected by straight black arrows showing data/control flow. White background, clear readable text labels inside the boxes, no 3D effects, no photorealism, highly structured.`;
    } else {
        stylePrompt = `A clean, professional electronic circuit schematic diagram of: ${coreSubject}. Style: Standard electrical symbols, white background, crisp black lines, clear component labels, 2D flat engineering style, no photorealism.`;
    }

    // Ensure total prompt length is within strict Imagen limits
    if (stylePrompt.length > 350) {
        stylePrompt = stylePrompt.substring(0, 350);
    }

    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: stylePrompt,
        config: {
            numberOfImages: 1,
            outputMimeType: 'image/jpeg',
            aspectRatio: '1:1', // Using default 1:1 to ensure maximum API compatibility
        },
    });
    
    if (!response.generatedImages || response.generatedImages.length === 0) {
        throw new Error("No image generated by the model.");
    }

    const base64ImageBytes = response.generatedImages[0].image.imageBytes;
    return `data:image/jpeg;base64,${base64ImageBytes}`;
};
